name: cryofire_new

channels:
  - defaults

dependencies:
  - python=3.7.10
  - anaconda::pip
  - pytorch::pytorch=1.13.0
  - pytorch::torchvision=0.14.0
  - pytorch::torchaudio=0.13.0
  - anaconda::cudatoolkit=11.3
  - conda-forge::matplotlib
  - jmcmurray::json
  - conda-forge::regex
  - anaconda::seaborn
  - anaconda::scipy
  - anaconda::scikit-learn
  - conda-forge::tensorboard=2.5.0
  - anaconda::jupyter
  - pip:
      - setuptools==59.5.0